CREATE SEQUENCE COURSE_ID_SEQ;
CREATE SEQUENCE STUDENT_ID_SEQ;
CREATE SEQUENCE TEACHER_ID_SEQ;
CREATE SEQUENCE STUDENTCOURSE_ID_SEQ;

CREATE TABLE COURSE
(COURSE_ID INT PRIMARY KEY NOT NULL DEFAULT NEXTVAL('COURSE_ID_SEQ'),
COURSENAME VARCHAR(50));

INSERT INTO COURSE (COURSENAME) VALUES ('.NET for Beginners');
INSERT INTO COURSE (COURSENAME) VALUES ('.NET Professional');
INSERT INTO COURSE (COURSENAME) VALUES ('ASP.NET');
INSERT INTO COURSE (COURSENAME) VALUES ('Web development');
INSERT INTO COURSE (COURSENAME) VALUES ('Python');

CREATE TABLE STUDENT
(STUDENT_ID INT PRIMARY KEY NOT NULL DEFAULT NEXTVAL('STUDENT_ID_SEQ'),
FIRSTNAME VARCHAR(50),
LASTNAME VARCHAR(50),
MIDDLENAME VARCHAR(50));

INSERT INTO STUDENT (FIRSTNAME, LASTNAME, MIDDLENAME) VALUES ('Иван', 'Иванов', 'Иванович');
INSERT INTO STUDENT (FIRSTNAME, LASTNAME, MIDDLENAME) VALUES ('Сергей', 'Сергеев', 'Сергеевич');
INSERT INTO STUDENT (FIRSTNAME, LASTNAME, MIDDLENAME) VALUES ('Константин', 'Константинов', 'Константинович');
INSERT INTO STUDENT (FIRSTNAME, LASTNAME, MIDDLENAME) VALUES ('Александр', 'Александров', 'Александрович');
INSERT INTO STUDENT (FIRSTNAME, LASTNAME, MIDDLENAME) VALUES ('Пётр', 'Петров', 'Петрович');

CREATE TABLE STUDENTCOURSE
(STUDENTCOURSE_ID INT PRIMARY KEY NOT NULL DEFAULT NEXTVAL('STUDENTCOURSE_ID_SEQ'),
COURSE_ID INT REFERENCES COURSE,
STUDENT_ID INT REFERENCES STUDENT
);

INSERT INTO STUDENTCOURSE (COURSE_ID, STUDENT_ID) VALUES (1, 1);
INSERT INTO STUDENTCOURSE (COURSE_ID, STUDENT_ID) VALUES (1, 2);
INSERT INTO STUDENTCOURSE (COURSE_ID, STUDENT_ID) VALUES (2, 1);
INSERT INTO STUDENTCOURSE (COURSE_ID, STUDENT_ID) VALUES (2, 2);
INSERT INTO STUDENTCOURSE (COURSE_ID, STUDENT_ID) VALUES (3, 3);
INSERT INTO STUDENTCOURSE (COURSE_ID, STUDENT_ID) VALUES (4, 4);
INSERT INTO STUDENTCOURSE (COURSE_ID, STUDENT_ID) VALUES (5, 5);

CREATE TABLE TEACHER
(TEACHER_ID INT PRIMARY KEY NOT NULL DEFAULT NEXTVAL('TEACHER_ID_SEQ'),
FIRSTNAME VARCHAR(50),
LASTNAME VARCHAR(50),
MIDDLENAME VARCHAR(50),
COURSE_ID INT REFERENCES COURSE);

INSERT INTO TEACHER (FIRSTNAME, LASTNAME, MIDDLENAME, COURSE_ID) VALUES ('Николай', 'Николаев', 'Николаевич', 1);
INSERT INTO TEACHER (FIRSTNAME, LASTNAME, MIDDLENAME, COURSE_ID) VALUES ('Игорь', 'Игорев', 'Игоревич', 1);
INSERT INTO TEACHER (FIRSTNAME, LASTNAME, MIDDLENAME, COURSE_ID) VALUES ('Алексей', 'Алексеев', 'Алексеевич', 2);
INSERT INTO TEACHER (FIRSTNAME, LASTNAME, MIDDLENAME, COURSE_ID) VALUES ('Юрий', 'Юрьев', 'Юрьевич', 3);
INSERT INTO TEACHER (FIRSTNAME, LASTNAME, MIDDLENAME, COURSE_ID) VALUES ('Илья', 'Ильин', 'Ильевич', 4);
INSERT INTO TEACHER (FIRSTNAME, LASTNAME, MIDDLENAME, COURSE_ID) VALUES ('Борис', 'Борисов', 'Борисович', 5);

select * from teacher
